language: swift
osx_image: xcode9.2
xcode_project: BirthdayReminder.xcworkspace
xcode_scheme: BirthdayReminder
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/mobileProvision.enc -d -a -out scripts/certs/XC_iOS_.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/privateKey.enc -d -a -out scripts/certs/dist.p12
- ./scripts/addKeys.sh
before_install:
- rvm use system
- sudo gem install cocoapods -v '1.5.0'
- sudo rm -fr ~/.cocoapods/repos/master
- pod setup
- pod install
script: xcodebuild -workspace BirthdayReminder.xcworkspace -scheme BirthdayReminder -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
notifications:
  slack: birthreminder:Nzv0j52r06OKMH5kAMZo0hJo
env:
  global:
  - APP_NAME="BirthdayReminder"
  - 'DEVELOPER_NAME="iPhone Distribution: xinge Mu (F248CK9C8M)"'
  - secure: Js14hFwcDkNqYU5lumbUVkAnQPx/l/Q2AdIx1MZldGNtdAtya22lZwymxEn+Jm/wwky1kxfGK238XUYiuWKuojkruli0qFI3787BgjaQdLka0e+UgW3kYYG55p0mm6WTr/TVqcGElYaw0WweyjwY5PzZmfOgBoOG7+y2MLwawMKxU6Nk34hgEsF/PHTvoTfaC6gTlSU/b7yigWJP3S1TEzYyWHxt25k/1q9vRIMZd7+ZbzIKn3dLHi+2tP8C6ChcmQ/XbEj7Am+igNX0xtyPPxRfzaS2wwLjhEiaJCCNhZQ5D46Z91xWyLMzrpewvDL9ii7hmRoLLZFZ37nRQXARh/+skWtlR7OVvEjXIInF0zMHHgGfuyO5lhPnGuEVsl5eKDgRmOoNk158jRijvksov4jQ/892hHGlMZqrWfQVrfMKGinzuKftjnT2oeUT/kPt7zIzG/dneGxsJCFyA84Yyl2+hBCwrWvOdaCGxPOXb7uGz+lRB2LYB8rEyjyxNf9u2eqaTNTZn5KXa01aV52XiLSiLtXbQy0QqpwDlTfkI2WmgutSMQQUoRaYW2KESGocGQWG/KLNFE3wAcA6PDl0o5iuX5W0U6GiYO6KaGY2h4q4tmHXiJTHPxEH66ht1apDWfUFoNQKx68s1x6hmnur0IyHsbS6cm5wZPqYf2psKSE=
  - secure: J2W3vHBJ+/+4ggWz3qGWs1aOQufZTPuVq1MZV/tLEdFB6Grp7Fp5wbHg9iLSz6GsyIQY5KdpLKcTFiM7mzavK8ybiqu0rMskXT/DJmAstlclJa1XSbIilqNBp1ft8Yn+AOWApKtPBQ5x1bmcrZupGORKsIUV1NUnivDlQ0s4HYWlTbfecUuvgTb+LC1I24Jrq6eYE3V1U/GDiK58oXp+2I3qV4K9r3BTyhYDgdrz4XsV33/DwLB5fdMsApXC0oml1EhJ8iE8q0tJg7zo2SmsQMExfIg2wmGHtjTGdUpHLoNU/v8jbepZzOPeESwVncjPyOjyalnB2HbXycHzjHVFcrtFRBL9mc0DaNIDvcvHTQ/qptqIz0KIlZYOwp+DxhS3wItMWfO1skvmdcOeT1qJa+rcnmy+W83LqVFpNYSXtQrrdcM50H0AW2y1kWd15FKPXKnM1Aqs1Pd5mRdv6h83zQs+VzdlwVs0IQOwa2KUyyDXAlf4Xu0me/TK+VXRjAITQxuHpmVn/Nc6KsS6lWiBzoDugTJeVTOOdJUTFN/jMyByyGJgsLVvThJZig2WqwTmWxIYfjos4m0zG6p8dl1wupMeaNz/7kFcHyj+1e1siTvMHpde7hkdiFk+se346rQ1zKrstyY8YeHPA01Gq7U7Dyqvkw0sZrzli8mSExFjJh0=
